language: node_js
node_js:
- lts/*
notifications:
  email: false
cache: yarn
stages:
- test
- pages
- release
jobs:
  include:
  - stage: test
    script: npm run build
  - stage: pages
    script:
    - npm run clean
    - npm run typedoc
    deploy:
      provider: pages
      local_dir: docs
      skip-cleanup: true
      github-token: "$GH_TOKEN"
      keep-history: true
      verbose: true
      on:
        branch: master
  - stage: release
    script:
    - npm run clean
    - npm run buildUpdate
    before_deploy:
    - cd dist
    deploy:
      provider: npm
      email: os.sandor@gmail.com
      skip_cleanup: true
      api_key:
        secure: crYTyc3zWwxCfmv/5Zuf9A3A+8fJe0jFaSNDPJH1LW8yiL2bGJSoT3ux0d8ASX+vA9yvlRrs7G5yAKuq5gctJTM/A+GISu/PQ6CibCpBZVSSSgpbv5CfTvOcOO/m5AraIAhelr85il1ceUVlDOVu5IYxtPA34y2fEvJmXIhfMKQNa2AkBiPZOjxST4iEDap+Wqoy1hXd1t6DKi4Ublb/DjtFAJi3ofos9f66JQ/w54bsJ22wV7gF4FYDgH8SCNEEtrKyGbfWSCfmH0L2m6anadj8Ais2AQ+Oea27E5vz6NiAHiSaTTwvyUSnqu3F4HN4wALRtjdusSgsl6uZM3fu0BlEfQ/H9LepnQPgR/EEdnmvSNC9YowIqNGZ0cf2cI+3ItK8CE1Qn61AZSjS+p4frxYAKGQBHVPXuSEPWbIEKIkMn0Mli8fFrBnP5VRwRFIVdq9T+0ymhgOK+EsXKgD5M3TF13FQOnxf/4SRi2cMH76yF3oWGh9VEYUBd6UVHWkjil+UPJR9vpHZAcs5A07DNjuCsr4Glzy4iNUsZRHxh71/iAKK2Uup9Jt598OH7C2PQUt9yEB//pS7uPmtsPYvHYqkllT4GW7Ydw8QOTbrA7iud2qc83Jik1LS985xK50jiYwDH6GaUCFuDD57217mpEtSRC+LX6+QLVFn0RGF8FQ=
      on:
        branch: master
        tags: true
        